"""add task table

Revision ID: edf22b82c2e4
Revises: 
Create Date: 2023-12-24 13:43:13.184638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf22b82c2e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('namespace', sa.String(length=64), nullable=False),
    sa.Column('runtime', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_update_at', sa.DateTime(), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=False),
    sa.Column('script', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_image'), ['image'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_namespace'), ['namespace'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_runtime'), ['runtime'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_runtime'))
        batch_op.drop_index(batch_op.f('ix_task_namespace'))
        batch_op.drop_index(batch_op.f('ix_task_name'))
        batch_op.drop_index(batch_op.f('ix_task_image'))

    op.drop_table('task')
    # ### end Alembic commands ###
